### ISSUE TITLE
Build packages by using CI services

### ISSUE THREAD

**Issue by jankatins** [IRkernel/irkernel.github.io#16]
There seems to be a CI service for all three major OSes and it is used by conda-forge to build conda packages for matplotlib on all of them. It should be possible to adapt this pattern to R and use that to upload all pushes to a central repo. On the a release, we would only copy the files to this repo. 

I haven't played with this, but examples can be found here: https://github.com/conda-forge

**Comment by jankatins** [comment]
It seems that you can't use `conda -c r r ...` to setup a fully functional build environment for R on windows, so at least the rzmq package won't be so easy :-( But our packages should be doable by using conda like illustrated in one of the conda-forge examples (with `conda -c r <build deps>`) and then simple find out where the build package is put and upload:
- Use a shallow clone with `--depth=1`
- copy package to dir
- call R to integrate the new package in the repo structure
- commit + push via a github token

Ah, and we get a conda channel with all out dev versions for free :-)

**Comment by asmeurer** [comment]
You'll need to install RTools for any compiled code. See https://github.com/conda/conda-recipes/blob/master/r-base/notes.md. 

Also note that I never got the latest version of R to build on Windows, so until someone figures it out, you'll need to build with `conda build --R 3.1.3`.

**Comment by jankatins** [comment]
@asmeurer ok, thanks! Not having a windows installer for 3.2 is bad news :-( any logs/bugreports somewhere?

**Comment by jankatins** [comment]
Ok, the conda not available in all versions is a bummer :-( That means the feedstock way is probably gone for now :-(

Ok, here are some more things:
- Building R packages (including native ones) via appveyor: https://github.com/krlmlr/r-appveyor/blob/master/scripts/appveyor-tool.ps1
- use travis to build OSX and linux builds: -> currently not possible for one repo, so either we do two or use a different CI service for linux... http://docs.travis-ci.com/user/multi-os/ http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/ 
- Use travis with objective-c to build on macosx and r-travis + CircleCI on linux with r-travis 

What's missing
- a way to build packages for more than one r version -> it seems at least the script for appveyor does not support that :-( https://github.com/krlmlr/r-appveyor/issues/2 It works on r-builder https://github.com/metacran/r-builder/blob/master/sample.travis.yml
- The way to manage the uploads.

I'm currently thinking about the following:
- dependencies are managed via travis/appveyor directly (one build env for all packages)
- A recipe is a file similar to a meta.yml for conda, but only URL + Tag. Just git clones the url + Tag
- It will also clone a copy of irkernel.github.io repo and add a new branch "package+tag", add the relevant file to the right place, commit and push (we should have a special user for this...). User + PW via the usual ways (secret env variables)
- Add a way to query irkernel.github.com for the current versions of a package and only build a "recipe" if the version is different

**Comment by flying-sheep** [comment]
we decided to use CRAN
