### ISSUE TITLE
Fix OSX release of rzmq

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/irkernel.github.io#18]
the rzmq-0.7.7.tgz is weird:
1. why does an OSX version contain a .so instead of a .dylib
2. why is there a `rzmq.so (mentat's conflicted copy).so`? which one is the right one?

could packagers in the future please not put code into dropbox, ever?

**Comment by takluyver** [comment]
Ah, thanks for checking that. I guess we need a Mac packager to rebuild it.

**Comment by flying-sheep** [comment]
we no longer use rzmq
