### ISSUE TITLE
Mobile layout transition to early, and no menu availlable.

### ISSUE THREAD

**Issue by Carreau** [IRkernel/irkernel.github.io#19]
The layout transition change at 850 pixels wide, which is super wide.
But the issue is on mobile layout you have no access on the manu to go to any of github repo. So I was like WTF how do I get to the irkernel repo. 

<img width="1136" alt="screen shot 2015-11-08 at 21 23 25" src="https://cloud.githubusercontent.com/assets/335567/11026456/0eed9dc6-865f-11e5-9bfa-8bd4e208fbf7.png">

Ok, 850 too wide is subjective opinion, also nitpicking but there is a second media transition at 840, so you might want to place the media transition at one specific width at the same time if you fix that.

**Comment by takluyver** [comment]
@flying-sheep , any thoughts? I haven't been involved in the website design at all.

**Comment by flying-sheep** [comment]
hmm, no real reason to hide it.
