### ISSUE TITLE
Readme not rendered correctly

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/irkernel.github.io#2]
That’s because redcarpet isn’t very good: vmg/redcarpet#230

dunno how to reshape README until it works on both https://github.com/IRkernel/IRkernel and https://irkernel.github.io/

**Comment by jankatins** [comment]
The only problem I saw was the MacPorts section, which is rendered as one big codeblock :-(

**Comment by flying-sheep** [comment]
redcarpet really can’t cope with nested lists. a damn shame. and kramdown doesn’t even have fenced code blocks.

i wonder why github doesn’t just provide its own markdown rendering engine for github pages.

**Comment by flying-sheep** [comment]
really amazing:
- [this](https://github.com/github/markup/blob/master/lib/github/markup/markdown.rb#L7) shows that they use the 'github/markdown' gem
- [which one can use](https://rubygems.org/gems/github-markdown/versions/0.6.8) from ruby but doesn’t have a public repo.
- and which isn’t usable from GH pages

wat.

**Comment by jankatins** [comment]
So use that? There is something about requiring gems in _config, maybe that helps? :-) I was also fighting with github pages rendering this weekend, but I only had the problem that codeblocks were not highlighted, which magically went away when I switched to redcarpet :-)

**Comment by jankatins** [comment]
Of this:

> In addition to the defaults mentioned above, you can also turn on recognition of Github Flavored Markdown by passing an input option with a value of “GFM”.
> For example, in your _config.yml:

```
kramdown:
  input: GFM
```

from http://jekyllrb.com/docs/configuration/#kramdown

**Comment by flying-sheep** [comment]
well, we can choose:
- code highlighting (redcarpet)
- a bit more correct markdown parsing (kramdown with your config)

no plugins or custom extensions allowed on GH pages afaik

**Comment by flying-sheep** [comment]
ha, your tip with kramdown+GFM gave the solution: we can simply switch to it + highlight.js!

**Comment by takluyver** [comment]
I'm not tracking this very closely, but http://irkernel.github.io/ looks pretty ugly right now, because it's interpreting line endings in the markdown source as HTML line breaks. Is there an easy way to make it not do that? https://github.com/IRkernel/IRkernel#native-r-kernel-for-ipython looks correct.

**Comment by flying-sheep** [comment]
i noticed that as well, and fixed it.

finally sane options for GH pages! yay!

**Comment by takluyver** [comment]
Thanks :-)
