### ISSUE TITLE
FAQ: add how to install packages

### ISSUE THREAD

**Issue by jankatins** [IRkernel/irkernel.github.io#22]
https://github.com/IRkernel/IRkernel/issues/234

from @flying-sheep 

The default is `install.packages(..., repos = getOption('repos'))`, which evaluates to `install.packages(..., repos = c(CRAN = '@CRAN@'))`

`@CRAN@` means “show a selector”, but IRkernel doesn’t identify as “interactive” yet, so interactive functions like popping up a repo selector doesn’t work.

therefore, you either have to call `install.packages(..., repos = c('https://...', ...))` every time, or `options(repos = c('https://...', ...))` once in your notebook (before the `install.packages`) call.

you can get something automatically by doing e.g.:

``` r
country.code <- 'de'  # use yours
url.pattern <- 'https://'  # use http if you want
repo.data.frame <- subset(getCRANmirrors(), CountryCode == country.code & grepl(url.pattern, URL))
options(repos = repo.data.frame$URL)
```

**Comment by jankatins** [comment]
[Actually I just wanted to add a new page but then I opened one of the pages and was scared by the raw html. Is there a converter from MD to material light or do I really have to write html by hand?]

**Comment by flying-sheep** [comment]
markdown isn’t extensible, so as soon as you want to use more features than what it has to offer, you either have to hack your markdown processor to accept just another dialect or write HTML anyway.

so yes, you have to write `<h1>...</h1>` instead of `# ...` and `<ol><li>...</ol>` instead of `1. ...`. is this really so much of an issue?

**Comment by jankatins** [comment]
It's more things like:

``` html
<aside class="card-note mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <i class="material-icons">warning</i>
        <div class="mdl-layout-spacer"></div>
        Important!
        <div class="mdl-layout-spacer"></div>
        <i class="material-icons">warning</i>
    </div>
    <div class="mdl-card__supporting-text">
        On OS X, be sure to execute this in R  started from the Terminal, not the R App!<br>
        (This is because the R app doesn’t honor <var>$PATH</var> changes in <samp>~/.bash_profile</samp>)
    </div>
</aside>

The kernel spec can be installed for the current user with the following line from R:
<pre class="r mdl-shadow--2dp"><code>IRkernel::installspec()</code></pre>
<p>To install system-wide, set <code>user</code> to False in the <code>installspec</code> command:</p>
<pre class="r mdl-shadow--2dp"><code>IRkernel::installspec(user = FALSE)</code></pre>
```

Instead of 

`````` markdown
### Important
On OS X, be sure to execute this in R  started from the Terminal, not the R App!

(This is because the R app doesn’t honor `$PATH` changes in `~/.bash_profile`)

The kernel spec can be installed for the current user with the following line from R:

​```r
IRkernel::installspec()
​```

To install system-wide, set `user` to `False` in the `installspec` command:

​```r
IRkernel::installspec(user = FALSE)
​```
``````

-> the additional classes (for syntax highlighting?) and substructure...

-> I would very much prefer that one could build the main text with markdown (can I still do that?  There is still a jeckyl YAML header...?).

**Comment by flying-sheep** [comment]
you’re right, MDL is pretty verbose. beware, rant following:

markdown is perfect for forums and issue trackers, but technical documentation really benefits from _semantics_, as they can be uniformly styled, crosslinked, indexed, … and as said: markdown isn’t extensible.

i would really love to see reStructuredText in more places, as it _is_ extensible, but it seems markdown is _so_ popular that people use it even in technical documentation, which is horribly shortsighted. rST (or asciidoc) would enable Rust and Swift to have easy crosslinks within and between symbols in API docs, but noo, let’s use fucking markdown, and have plain dumb unclickable ``ClassName`` code fragments everywhere when `:class:`ClassName`` would be enough in rST to get a semantically styled link.

> I would very much prefer that one could build the main text with markdown (can I still do that? There is still a jeckyl YAML header...?).

yes, it used to be done this way until i needed more complex formatting. you can search the git history to find how i used to do it.

**Comment by flying-sheep** [comment]
and btw: your markdown doesn’t convert to the html above. your markdown converts to this:

``` html
<h3>Important</h3>
On OS X, be sure to execute this in R  started from the Terminal, not the R App!

(This is because the R app doesn’t honor <code>$PATH</code> changes in <code>~/.bash_profile</code>)

The kernel spec can be installed for the current user with the following line from R:

<pre><code class=r>IRkernel::installspec()</code></pre>

To install system-wide, set <code>user</code> to <code>False</code> in the <code>installspec</code> command:

<pre><code class=r>IRkernel::installspec(user = FALSE)</code></pre>
```

and this is remarkably similar to the PDF i wrote with all semantic information except for the code block language stripped off
