### ISSUE TITLE
FAQ: We don’t support %%magic

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/irkernel.github.io#26]
we don’t support `%%HTML` magic, but nonmagical `IRdisplay::display_html()`

see IRkernel/IRkernel#260

**Comment by jeremydouglass** [comment]
Please correct comment of Apr 19 to: "but nonmagical IRdisplay::display_html()"

`IRdisplay` is miswritten `IRDisplay`, which will fail to import / run in ways that may seem mysterious.

**Comment by takluyver** [comment]
Thanks @jeremydouglass , fixed. :-)
