### ISSUE TITLE
remove repo

### ISSUE THREAD

**Issue by jankatins** [IRkernel/irkernel.github.io#30]
It's currently totally out of date, not needed anymore since the switch to the new zmq lib and  `install_github` is even clearer until we have all packages on CRAN.

**Comment by takluyver** [comment]
Let's leave it at least until the packages are on CRAN. It's not doing any harm by being there.

**Comment by jankatins** [comment]
ok...

**Comment by flying-sheep** [comment]
hmm, i guess it is if people install the ancient stuff.

see e.g. IRkernel/IRkernel#397

let’s remove it now
