### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by takluyver** [IRkernel/irkernel.github.io#31]
![screenshot from 2016-05-15 09-07-25](https://cloud.githubusercontent.com/assets/327925/15272796/86ed49dc-1a7c-11e6-8ed8-07d74dae7486.png)

**Comment by flying-sheep** [comment]
cannot confirm: 

![spectacle sa2829](https://cloud.githubusercontent.com/assets/291575/15277184/ba174a9e-1afc-11e6-9b98-e370e6231ff3.png)

**Comment by takluyver** [comment]
My mistake - at some point Google Fonts was having problems and making a bunch of sites really slow to load, so I edited `/etc/hosts` to block it. Then I predictably forgot that I had done so.

Side rant: This should never have been necessary if web designers stuck to graceful degradation. Fancy fonts taking a long time to load should never mean I can't read the page. But they have to avoid the 'Flash of Unstyled Content', so they hide the page until everything is ready :angry:

**Comment by flying-sheep** [comment]
i’m not a fan of using fonts for icons anyway, but that’s what material design lite used so i went with it.

we can upgrade to [SVG](http://google.github.io/material-design-icons/#icon-images-for-the-web) now if we want.

**Comment by takluyver** [comment]
Up to you with SVG - using a font doesn't bother me except when I break it with my config ;-)

**Comment by jankatins** [comment]
Is there anything for R which is like sphinx, i.e. something which could generate a website including API documentation?

**Comment by flying-sheep** [comment]
http://yihui.name/en/2012/10/build-static-html-help/
