### ISSUE TITLE
Source installation instructions out of date?

### ISSUE THREAD

**Issue by ivirshup** [IRkernel/irkernel.github.io#34]
The commands for source installation instructions say to install `rzmq` while `IRkernel` uses `pbdzmq`.

I believe this has come up in [some](https://github.com/IRkernel/IRkernel/issues/357) [issues](https://github.com/IRkernel/IRkernel/issues/326) for IRkernel.

If I'm not mistaken, shouldn't the commands be the same as for installing from binary?

**Comment by takluyver** [comment]
Where are these commands? I've just had a quick look and I don't see anything mentioning rzmq.

**Comment by ivirshup** [comment]
I see them under [linux install](http://irkernel.github.io/installation/#linux-panel), [OSX install](http://irkernel.github.io/installation/#os-x-panel), and a reference to rzmq ("You'll need zmq development headers to compile rzmq") is at the top of [install page](http://irkernel.github.io/installation/#source-panel).

Images:

![screen shot 2016-07-29 at 8 26 49 pm](https://cloud.githubusercontent.com/assets/8238804/17245682/e4686ad6-55ca-11e6-8a73-283b3d86ebd2.png)
![screen shot 2016-07-29 at 8 26 57 pm](https://cloud.githubusercontent.com/assets/8238804/17245685/f085cc32-55ca-11e6-88ef-8d4d42a072b1.png)

**Comment by flying-sheep** [comment]
thanks! you still possibly need ZMQ development headers AFAIK, but of course not for rZMQ.

**Comment by takluyver** [comment]
Ah, thanks, I hadn't spotted those pages on the website.
