### ISSUE TITLE
Host docs

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/irkernel.github.io#35]
I just create this to immediately celebrate its closing via 3a098a0bc856edc15858a8b9102d44b356ea3cae

we have glorious docs with a script autobuilding them, with cool URLs and all!

http://irkernel.github.io/docs/repr/0.8/repr_-times-.recordedplot.html#examples

the idea was to have docs for all releases that we bothered to write a description for. renaming of the files splitting/merging topics for aliases, or removal of sections won’t cause link breakage.

:tada: @takluyver @janschulz

**Comment by takluyver** [comment]
Nice! :+1:
