### ISSUE TITLE
Instructions for installation on Ubuntu (at least cosmic) aren't correct

### ISSUE THREAD

**Issue by TsukiZombina** [IRkernel/irkernel.github.io#44]
The installation at https://irkernel.github.io/installation/#linux-panel for Ubuntu say to execute:
sudo apt-get install libzmq3-dev libcurl-openssl1.0-dev libssl-dev
but it should be:
sudo apt-get install libzmq3-dev libcurl4-openssl-dev libssl-dev jupyter-core jupyter-client
like it's in Debian.
It gave me the same errors and solved it as in #596 .

**Comment by flying-sheep** [comment]
Fixed in 84e76501bc85745e0d937be02f721e06f552f471
